name: intlx
version: 0.0.1
author: Sean Eagan <seaneagan1@gmail.com>
homepage: http://www.github.com/seaneagan/intlx
description: >
  Intlx is experimental internationalization APIs for Dart, 
  which have not yet made it into the intl package itslef.
  All data is sourced from CLDR.
dependencies:
  intl: { sdk: intl }
  unittest: { sdk: unittest }