name: intlx
version: 0.2.1
author: Sean Eagan <seaneagan1@gmail.com>
description: Intlx is internationalization APIs for Dart,  which have not yet made it into the intl package itself.  All data is sourced from CLDR.
homepage: http://www.github.com/seaneagan/intlx
dependencies:
  intl: any
dev_dependencies:
  unittest: any
  http: any
  browser: any
  web_ui: any
  parsers: any
  pathos: any
  widget: any
